import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/providers/AuthProvider";
import NextTopLoader from "nextjs-toploader";
import { ThemeProvider } from "@/providers/ThemeProvider";
import ToasterContext from "@/context/ToasterContext";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <NextTopLoader
          color="#7C3AED"
          crawlSpeed={200}
          height={4}
          crawl={true}
          easing="ease"
        />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ToasterContext />
          <AuthProvider>{children}</AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
